#!/bin/bash

# Variables
input="$1"
pebbleName=$(pactl list | grep -m 1 "Name: alsa_output.usb-ACTIONS_Pebble" | cut -d ' ' -f2)
headSetName=$(pactl list | grep -m 1 "Name: alsa_output.usb-Corsair_CORSAIR_VIRTUOSO_SE_Wireless_Gaming_Headset" | cut -d ' ' -f2)
usb=$(ls /media/berardinux)

# Connect to Soundbar speaker!!
function sound_bar {
  soundbar_mac="54:15:89:70:13:68"
  pactl set-default-sink bluez_output.54_15_89_70_13_68.1

  is_connected=$(bluetoothctl << EOF
  info $Soundbar_mac
EOF
  )

  if [[ $is_connected =~ "Connected: yes" ]]; then
    echo "It is connected"
  else
    bluetoothctl << EOF
    power on
    scan on
EOF
    sleep 5
    bluetoothctl << EOF
    pair $soundbar_mac
    connect $soundbar_mac
EOF
    sleep 5
    bluetoothctl << EOF
    exit
EOF
    echo "Bluetooth connection to Samsung Soundbar established."
  fi
}

function Eject {
  echo "--   Checking for Disk...   --"
  disk=$(lsblk | grep sr | cut -d" " -f1)
  if echo $disk > /dev/null; then
    if mount | grep sr0; then
      echo "--     Disk Drive Found    --"
      echo "--       Disk Mounted       --"
      eject /dev/$disk
      echo "--       Disk Ejected       --"
    else
      echo "--     Disk Drive Found     --"
      echo "--     Disk Not Mounted     --"
    fi
  else
    echo "--     No Disk Drive Found     --"
  fi
  flashNum=$(($(find /media/berardinux/ -maxdepth 1 -type f -o -type d | wc -l) - 1))

  if ls /media/berardinux > /dev/null; then
    if [ "$flashNum" -gt 1 ]; then
      echo "-- There are $flashNum Flash Drives --"
      umount /media/$USER/*
      ((flashNum--))
      echo "-- All Flash Drives Ejected --"
    else
      echo "-- There is One Flash Drive --"
      flash=$(ls /media/berardinux)
      umount "/media/$USER/"$flash""
      echo "--   Flash Drive Ejected    --"
    fi
  else
    echo "-- There are no Flash Drives Mounted --"
  fi
}

case $input in
  "0")
    nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
    ;;
  "1")
    xrandr --output DP-2 --mode 1920x1080
    xrandr --output HDMI-0 --off --output DP-4 --mode 2560x1440 --rate 240 --pos 640x2160 --primary --output DP-2 --mode 3840x2160 --rate 155 --pos 0x0
    ;;
  "2")
    xrandr --output HDMI-0 --off --output DP-4 --mode 2560x1440 --rate 240 --pos 0x0 --primary --output DP-2 --off
    ;;
  "3")
    xrandr --output DP-2 --mode 1920x1080
    xrandr --output HDMI-0 --mode 3840x2160 --rate 60 --pos 0x0 --primary --output DP-4 --off --output DP-2 --mode 3840x2160 --rate 60 --pos 0x0
    ;;
  "4")
    pactl set-default-sink $pebbleName
    ;;
  "5")
    pactl set-default-sink $headSetName
    ;;
  "6")
    sound_bar
    ;;
  "-e")
    Eject
    ;;
  *)
    echo "Boo, That wasn't a option!"
    ;;
esac



